# Generated by Django 4.0 on 2022-01-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_alter_picture_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='fornecedor')),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='novo'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='negociável')),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.baseproduct')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='base_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.baseproduct', verbose_name='produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.baseproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='base_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.baseproduct', verbose_name='produto'),
            preserve_default=False,
        ),
    ]
