# Generated by Django 4.0 on 2022-08-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text='Determina se a compra do carrinho está em aberto.', verbose_name='Carrinho em aberto')),
            ],
            options={
                'verbose_name': 'carrinho de compras',
                'verbose_name_plural': 'carrinhos de compras',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(verbose_name='unidades')),
            ],
            options={
                'verbose_name': 'item do carrinho',
                'verbose_name_plural': 'itens dos carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight', models.FloatField(verbose_name='frete')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
            },
        ),
    ]
