# Generated by Django 4.0 on 2022-09-07 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_address_is_main_alter_user_favorites'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Determina se a cesta de compras está ativa.', verbose_name='ativa')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'cesta de compras',
                'verbose_name_plural': 'cestas de compras',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight', models.FloatField(verbose_name='frete')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data')),
                ('note', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('installments', models.IntegerField(choices=[(1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')], default=1, verbose_name='parcelas')),
                ('basket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.basket', verbose_name='cesta de compras')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(verbose_name='unidades')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.basket', verbose_name='cesta de compras')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.baseproduct', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item da cesta',
                'verbose_name_plural': 'itens da cesta',
            },
        ),
    ]
