# Generated by Django 4.0 on 2022-01-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_service_options_alter_product_is_new'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('freight', models.FloatField(verbose_name='frete')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='comprador')),
            ],
            options={
                'verbose_name': 'carrinho de compras',
                'verbose_name_plural': 'carrinhos de compras',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(verbose_name='unidades')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.cart', verbose_name='carrinho de compras')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.baseproduct', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item do carrinho',
                'verbose_name_plural': 'itens dos carrinhos',
            },
        ),
    ]
