# Generated by Django 4.0 on 2022-02-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Determina se a compra do carrinho está em aberto.', verbose_name='Carrinho em aberto'),
        ),
    ]
