# Generated by Django 4.0 on 2022-08-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='endereço de email')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='nome')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='sobrenome')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('is_staff', models.BooleanField(default=False, help_text='Define se o usuário tem permissão de entrar no site administrativo.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Define se o usuário deve ser tratado como ativo. Desmarque este campo ao invés de deletar usuários.', verbose_name='ativo')),
                ('is_trusty', models.BooleanField(default=False, help_text='Define se o usuário confirmou seu e-mail.', verbose_name='confiável')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('birth_date', models.DateTimeField(null=True, verbose_name='date de nascimento')),
                ('gender', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Outro')], max_length=1, null=True, verbose_name='Unidade de Medida')),
                ('favorites', models.ManyToManyField(to='core.BaseProduct', verbose_name='favoritos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddi', models.IntegerField(verbose_name='DDI')),
                ('ddd', models.IntegerField(verbose_name='DDD')),
                ('number', models.IntegerField(unique=True, verbose_name='número')),
                ('is_main', models.BooleanField(verbose_name='telefone principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='país')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('city', models.CharField(max_length=50, verbose_name='cidade')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('address1', models.CharField(max_length=100, verbose_name='lagradouro')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('is_main', models.BooleanField(default=True, verbose_name='endereço principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='usuário')),
            ],
        ),
    ]
