# Generated by Django 4.0.3 on 2022-04-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='core.baseproduct', verbose_name='favoritos'),
        ),
    ]
