# Generated by Django 4.0 on 2022-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_quantity'),
        ('users', '0002_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='endereço principal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='core.BaseProduct', verbose_name='favoritos'),
        ),
    ]
