# Generated by Django 4.0 on 2022-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_is_main_alter_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default='1900-01-01', verbose_name='date de nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Outro')], default='', max_length=1, verbose_name='Unidade de Medida'),
            preserve_default=False,
        ),
    ]
