name: Aplicação Django
on: [pull_request]
jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
      SECRET_KEY: "5prjtjdp9)69ty=*c_68erb&sf+n8d)5go_=$$@2-sv@#jd(r8"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up do Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Instalar Depenências
      run: |
        pip install pipenv
        pipenv sync --dev
    - name: Rodar Testes Automaticos
      run: |
        pipenv run pytest liberaction